MRP.Web/Models/ErrorViewModel.cs
namespace MRP.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MRP.Web/Controllers/AccountController.cs
using Application.DTOs;
using Application.Features.User.Commands;
using Application.Features.User.Queries;
using MediatR;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Text.Json;

namespace MRP.Web.Controllers
{
    public class AccountController : Controller
    {
        private IMediator _mediator;
        protected IMediator Mediator => _mediator ??= HttpContext.RequestServices.GetService<IMediator>();
        public IActionResult Login(string returnUrl = null)
        {
            if (HttpContext.User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Home");
            TempData["ReturnUrl"] = returnUrl;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginUserQuery loginUserQuery)
        {
            var response = await Mediator.Send(loginUserQuery);
            if (response.Succeeded)
            { 
                if (response.Message != null)
                {
                    await HttpContext.Session.LoadAsync();
                    await LoginProcess(response.Data);
                    await HttpContext.Session.CommitAsync();
                }
                else
                {
                    try
                    {
                        await LoginProcess(response.Data);

                    }
                    catch (Exception ex)
                    {

                    }
                }
            }
            return Ok(response);

        }
        [HttpPost]
        public async Task<IActionResult> AddUser(AddUserCommand command)
        {
            var response = await Mediator.Send(command);
            return Json(response);
        }
        private async Task LoginProcess(UserLoginDto user)
        {

            var claims = new List<Claim>
    {
        new Claim(ClaimTypes.Name, user.UserName),
        new Claim(ClaimTypes.Role, user.IsAdmin ? "Admin" : "User")
    };

            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity));
            HttpContext.Session.SetString("currentUser",
                JsonSerializer.Serialize(user));
        }
        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            HttpContext.Session.Clear();

            return RedirectToAction("Login", "Account");
        }
    }

}

MRP.Web/Controllers/AdminController.cs
using Application.Features.MeetingRoom.Features;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Reflection.Metadata.Ecma335;

namespace MRP.Web.Controllers
{
    [Authorize(Roles ="Admin")]
    public class AdminController:Controller
    {
        private IMediator _mediator;
        protected IMediator Mediator => _mediator ??= HttpContext.RequestServices.GetService<IMediator>();
        [HttpGet]
        public IActionResult AddMeetingRoom()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddMeetingRoom(CreateMeetingRoomCommand command)
        {
            var result = await Mediator.Send(command);

            return Json(result);
        }
    }
}

MRP.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MRP.Web.Models;
using System.Diagnostics;

namespace MRP.Web.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MRP.Web/Controllers/MeetingController.cs
using Application.DTOs;
using Application.Features.MeetingRoom.Querie;
using Application.Features.Meetings.Commands;
using Application.Features.Meetings.Queries;
using Application.Features.Reservations.Command;
using Application.Features.Reservations.Query;
using Domain.Entities;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Cryptography.X509Certificates;

namespace MRP.Web.Controllers
{
    [Authorize]
    public class MeetingController:Controller
    {
        private IMediator _mediator;
        protected IMediator Mediator => _mediator ??= HttpContext.RequestServices.GetService<IMediator>();

        public MeetingController(IMediator mediator)
        {
            _mediator = mediator;
        }
        [HttpGet]
        public async Task<IActionResult> CreateMeeting()
        {
            var model = await Mediator.Send(new GetCreateMeetingRoomQuery(User.Identity.Name));
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> GetAllMeetingUser(Guid? id,DateTime start, DateTime end)
        {
            var users = await Mediator.Send(
                new GetAllMeetingUsersQuery(id,start.Date, start, end));

            return Json(users);
        }
        [HttpGet]
        public async Task<IActionResult> GetRoomReservations(Guid roomId)
        {
            var events = await Mediator.Send(new GetRoomReservationQuery(roomId));
            return Json(events);
        }
        [HttpPost]
        public async Task<IActionResult> CreateReservation([FromBody] CreateReservationDto reservation)
        {
            var response = await Mediator.Send(new CreateReservationCommand(reservation, User.Identity.Name));
            return Ok(response);
        }
        [HttpGet]
        public async Task<IActionResult> PersonMeetingList()
        {
            
            var list = await Mediator.Send(new GetUserPersonMeetingListQuery(User.Identity.Name));
            return View(list);
        }
        [HttpGet]
        public async Task<IActionResult> CreatedMeetingList()
        {
            var list = await Mediator.Send(new GetUserCreaterPersonMeetingListQuery(User.Identity.Name));
            return View(list);
        }
        [HttpPost]
        public async Task<IActionResult> AddParticipant([FromBody] MettingAddParticipant model)
        {
            var response = await Mediator.Send(new AddParticipantCommand(model));
            return Ok(response);
        }
        [HttpPost]
        public async Task<IActionResult> RemoveParticipant([FromBody] MettingAddParticipant model)
        {
            var currentUser = User.Identity.Name;
            var response = await Mediator.Send(new RemoveParticipantCommand(model, currentUser));
            return Ok(response);
        }
    }
}

MRP.Web/Controllers/UsersController.cs
using Application.Features.User.Commands;
using Application.Features.User.Queries;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace MRP.Web.Controllers
{
    public class UsersController:Controller
    {
        private IMediator _mediator;
        protected IMediator Mediator => _mediator ??= HttpContext.RequestServices.GetService<IMediator>();
        public async Task<IActionResult> Index()
        {
            var allUser = await Mediator.Send(new GetAllUsersQuery());
            return View(allUser);
        }
        [HttpPost]
        public async Task<IActionResult> ChangeStatuse(Guid id)
        {
            var changeStatus = await Mediator.Send(new ChangeUserStatusCommand(id));
            return Ok(changeStatus);
        }
    }
}

MRP.Web/Views/Admin/AddMeetingRoom.cshtml
@model Application.Features.MeetingRoom.Features.CreateMeetingRoomCommand

@{
    ViewData["Title"] = "Toplantı Salonu Ekle";
}

<h2>Toplantı Odası Ekle</h2>

<form id="meetingRoomForm">
    <div class="mb-3">
        <label asp-for="Description" class="form-label">Açıklama</label>
        <input asp-for="Description" class="form-control" />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Location" class="form-label">Konum</label>
        <input asp-for="Location" class="form-control" />
        <span asp-validation-for="Location" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Capacity" class="form-label">Kapasitesi</label>
        <input asp-for="Capacity" type="number" class="form-control" />
        <span asp-validation-for="Capacity" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Kaydet</button>
</form>

<div id="resultMessage" class="mt-3"></div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />

    <script>
        $("#meetingRoomForm").submit(function (e) {
            e.preventDefault();

            $.ajax({
                url: '@Url.Action("AddMeetingRoom", "Admin")',
                type: 'POST',
                data: $(this).serialize(),
                success: function (response) {
                    if (response.succeeded || response.data === true) {
                        $("#resultMessage").html("<div class='alert alert-success'>Toplantı odası başarıyla eklendi.</div>");
                        $("#meetingRoomForm")[0].reset();
                    } else {
                        $("#resultMessage").html("<div class='alert alert-danger'>Bir hata oluştu.</div>");
                    }
                },
                error: function () {
                    $("#resultMessage").html("<div class='alert alert-danger'>Sunucu hatası.</div>");
                }
            });
        });
    </script>
}

MRP.Web/Views/Admin/Reservation.cshtml
@model List<Application.DTOs.AdminReservationDTO>

<div class="container mt-4">
    <h3 class="fw-bold mb-4">Tüm Rezervasyonlar</h3>

    <table class="table table-bordered table-hover">
        <thead class="table-dark">
            <tr>
                <th>Tarih</th>
                <th>Saat</th>
                <th>Toplantı Odası</th>
                <th>Durum</th>
                <th>Kullanıcılar</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                var collapseId = "users_" + item.Id;

                <tr>
                    <td>@item.Date</td>
                    <td>@item.Start - @item.End</td>
                    <td>@item.MeetingRoomName</td>

                    <td>
                        <span class="badge"
                              style="background-color:@item.BackgroundColor;
                            color:@item.TextColor;
                            border:1px solid @item.BorderColor;">
                            @item.StatusName
                        </span>
                    </td>

                    <td>
                        <button class="btn btn-sm btn-outline-primary"
                                data-bs-toggle="collapse"
                                data-bs-target="#@collapseId">
                            Kullanıcıları Göster
                        </button>
                    </td>
                </tr>

                <tr class="collapse" id="@collapseId">
                    <td colspan="5">
                        <div class="p-3 bg-light rounded">
                            <ul class="list-group">
                                @foreach (var user in item.UserList)
                                {
                                    <li class="list-group-item d-flex justify-content-between">
                                        <span>@user.FullName</span>

                                        @if (user.IsCreator)
                                        {
                                            <span class="badge bg-success">Oluşturan</span>
                                        }
                                    </li>
                                }
                            </ul>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

MRP.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>



</div>

MRP.Web/Views/Meeting/CreateMeeting.cshtml
@model Application.DTOs.UserCreateMeetingDTO

<div class="container mt-4">

    <h3 class="mb-4 fw-bold">Toplantı Odaları</h3>

    <div class="row">

        @foreach (var room in Model.MeetingsRoom)
        {
            <div class="col-md-4 mb-4">
                <div class="card shadow border-0 text-center h-100">
                    <div class="card-body">

                        <h5 class="fw-bold">@room.Name</h5>
                        <p class="text-muted">@room.Location</p>

                        <span class="badge bg-primary mb-3">
                            Son 2 Haftalık Talep: @room.TotalRequest
                        </span>

                        <div>
                            <button class="btn btn-dark btn-sm"
                                    onclick="openCalendar('@room.Id', '@room.Name')">
                                Takvimi Aç
                            </button>
                        </div>

                    </div>
                </div>
            </div>
        }

    </div>
    <div class="mb-3">
        <label class="form-label fw-bold">Toplantı Konusu</label>
        <input type="text"
               id="meetingSubject"
               class="form-control"
               placeholder="Toplantı konusunu giriniz..." />
    </div>
 
    <div class="row mt-4">
        <div class="col-12">
            <div class="card shadow border-0"
                 id="calendarWrapper"
                 style="display:none;">
                <div class="card-body">
                    <h5 id="selectedRoomTitle" class="fw-bold mb-3"></h5>
                    <div id="mainCalendar"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="card mt-4 shadow" id="reservationPanel" style="display:none;">
        <div class="card-body">

            <h5 class="fw-bold">Rezervasyon Oluştur</h5>

            <p id="selectedTimeText" class="text-muted"></p>

            <div id="userList" class="mb-3"></div>

            <button class="btn btn-primary" onclick="saveReservation()">
                Rezervasyonu Kaydet
            </button>

        </div>
    </div>
</div>

@section Scripts {
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.11/index.global.min.js"></script>
    <script>

        let calendar;

        function openCalendar(roomId, roomName) {

        const wrapper = document.getElementById("calendarWrapper");
        const title = document.getElementById("selectedRoomTitle");
        const startOfWeek = getStartOfWeek(new Date());
        const endOfNextWeek = getEndOfNextWeek(startOfWeek);
        wrapper.style.display = "block";
        title.innerText = roomName + " Takvimi";

        if (calendar) calendar.destroy();

        calendar = new FullCalendar.Calendar(
        document.getElementById("mainCalendar"),
        {
        initialView: 'timeGridWeek',
        locale: 'tr',
        firstDay: 1,
        height: 650,
        selectable: true,
        unselectAuto: false,
        slotMinTime: "09:00:00",
        slotMaxTime: "18:00:00",
        slotDuration: "00:30:00",
        allDaySlot: false,

        headerToolbar: {
        left: 'prev,next today',
        center: 'title',
        right: 'timeGridWeek,timeGridDay'
        },

        buttonText: {
        today: 'Bugün',
        week: 'Hafta',
        day: 'Gün'
        },
        
        validRange: {
        start: startOfWeek,
        end: endOfNextWeek,
        },

        selectable: true,
        selectMirror: true,

        select: function (info) {


        const start = info.start;
        const end = info.end;

        window.selectedStart = start;
        window.selectedEnd = end;
        window.selectedRoomId = roomId;

        const formatTR = (d) =>
        d.toLocaleString("tr-TR", {
        year: "numeric",
        month: "2-digit",
        day: "2-digit",
        hour: "2-digit",
        minute: "2-digit"
        });

        document.getElementById("reservationPanel").style.display = "block";
        document.getElementById("selectedTimeText").innerText =
        formatTR(start) + " - " + formatTR(end);

        fetch(`/Meeting/GetAllMeetingUser?start=${formatForBackend(start)}&end=${formatForBackend(end)}`)
        .then(res => res.json())
        .then(users => {

        let html = '';

        users.forEach(u => {
        if (u.isAvailable) {
        html += `
        <div class="form-check">
        <input class="form-check-input userCheck"
        type="checkbox"
        value="${u.id}"
        id="user_${u.id}">
        -<label class="form-check-label" for="user_${u.id}">
        ${u.userFullName}
        </label>
        </div>
        `;
        } else {
        html += `
        <div class="form-check">
        <input class="form-check-input"
        type="checkbox"
        disabled>
        <label class="form-check-label text-danger">
        ${u.userFullName} (Meşgul)
        </label>
        </div>
        `;
        }

        });

        document.getElementById("userList").innerHTML = html;
        });
        },

        events: function (fetchInfo, successCallback) {

        fetch(`/Meeting/GetRoomReservations?roomId=${roomId}`)
        .then(res => res.json())
        .then(data => successCallback(data));
        }
        }
        );

        calendar.render();

        window.scrollTo({
        top: wrapper.offsetTop - 100,
        behavior: "smooth"
        });
        }
        function saveReservation() {
        const subject = document.getElementById("meetingSubject").value;
        if (!subject || subject.trim() === "") {
            Swal.fire("Hata", "Toplantı konusu zorunludur.", "error");
            return;
        }
        const checkedUsers = [];
        document.querySelectorAll(".userCheck:checked")
        .forEach(x => checkedUsers.push(x.value));

        if (checkedUsers.length === 0) {
        alert("En az 1 katılımcı seçmelisiniz.");
        return;
        }

        const start = window.selectedStart;
        const end = window.selectedEnd;

        const payload = {

        roomId: window.selectedRoomId,
        Start: toLocalIsoNoZ(window.selectedStart),
        End: toLocalIsoNoZ(window.selectedEnd),
        subject:subject,
        date: start.toISOString().split("T")[0],
        startTime: start.toTimeString().slice(0,5),
        endTime: end.toTimeString().slice(0,5),
        participantIds: checkedUsers
        };

        console.log("Gönderilen payload:", payload);

        fetch('/Meeting/CreateReservation', {
        method: 'POST',
        headers: {
        'Content-Type': 'application/json'
        },
        body: JSON.stringify(payload)
        })
        .then(res => res.json())
        .then(data => {

        if (data.succeeded) {

        Swal.fire({
        icon: 'success',
        title: 'Başarılı',
        text: data.message
        });

        calendar.refetchEvents();
        document.getElementById("reservationPanel").style.display = "none";

        } else {

        Swal.fire({
        icon: 'error',
        title: 'Hata',
        text: data.message
        });
        }

        })
        .catch(err => {
        console.error(err);
        Swal.fire("Sunucu hatası oluştu");
        });
        }
        function toLocalIsoNoZ(d) {
        const pad = (n) => String(n).padStart(2, '0');
        return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}:00`;
        }
        const formatForBackend = (d) => {
        return d.getFullYear() + "-" +
        String(d.getMonth() + 1).padStart(2, "0") + "-" +
        String(d.getDate()).padStart(2, "0") + " " +
        String(d.getHours()).padStart(2, "0") + ":" +
        String(d.getMinutes()).padStart(2, "0");
        };
        function getStartOfWeek(date) {
            const d = new Date(date);
            const day = d.getDay();
            const diff = (day === 0 ? -6 : 1) - day;
            d.setDate(d.getDate() + diff);
            d.setHours(0, 0, 0, 0);
            return d;
        }
        function getEndOfNextWeek(startOfWeek) {
            const end = new Date(startOfWeek);
            end.setDate(end.getDate() + 13);
            end.setHours(23, 59, 59, 999);
            return end;
        }
    </script>

}

MRP.Web/Views/Meeting/PersonMeetingList.cshtml
@model List<Application.DTOs.MeetingsDTO>

<div class="container mt-4">
    <h3>Toplantı Listesi</h3>

    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Toplantı Konusu</th>
                <th>Tarih</th>
                <th>Başlangıç</th>
                <th>Bitiş</th>
                <th>Oda</th>
                <th>İşlem</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                var collapseId = "users_" + item.Id;

                <tr>
                    <td>@item.Subject</td>
                    <td>@item.Date</td>
                    <td>@item.StartDate</td>
                    <td>@item.EndDate</td>
                    <td>@item.RoomName</td>
                    <td>
                        <button class="btn btn-primary btn-sm"
                                data-bs-toggle="collapse"
                                data-bs-target="#@collapseId">
                            Kullanıcılar
                        </button>
                    </td>
                </tr>

                <tr class="collapse" id="@collapseId">
                    <td colspan="6">
                        <div class="p-3 bg-light rounded">
                            <strong>Katılımcılar:</strong>
                            <ul class="list-group mt-2">
                                @foreach (var user in item.MeetingPersson)
                                {
                                    <li class="list-group-item d-flex justify-content-between">
                                        <span>@user.FullName</span>
                                        @if (user.IsCreator)
                                        {
                                            <span class="badge bg-success">Oluşturan</span>
                                        }
                                    </li>
                                }
                            </ul>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

MRP.Web/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@{
    var isAuthenticated = User.Identity.IsAuthenticated;
    var isAdmin = User.IsInRole("Admin");
    var userName = User.Identity.Name;
}

<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MRP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0/dist/css/select2.min.css" rel="stylesheet" />
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow">
        <div class="container-fluid">

            <a class="navbar-brand fw-bold" asp-controller="Home" asp-action="Index">
                MRP Yönetim
            </a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMain">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarMain">

                @if (isAuthenticated)
                {
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Meeting" asp-action="CreateMeeting">
                                Toplantı Oluştur
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Meeting" asp-action="CreatedMeetingList">
                                Toplantı Başvurularım
                            </a>
                        </li>
                        

                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Meeting" asp-action="PersonMeetingList">
                                Katılacağım Toplantılar
                            </a>
                        </li>

                        @if (isAdmin)
                        {
                            <!-- SADECE ADMIN -->
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-warning"
                                       href="#"
                                       role="button"
                                       data-bs-toggle="dropdown"
                                       aria-expanded="false">
                                    Yönetim Paneli
                                </a>

                                <ul class="dropdown-menu dropdown-menu-dark">
                                    <li>
                                        <a class="dropdown-item"
                                               asp-controller="Users"
                                               asp-action="Index">
                                            Kullanıcılar
                                        </a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item"
                                               asp-controller="Reservations"
                                               asp-action="Index">
                                            Rezervasyonlar
                                        </a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item"
                                               asp-controller="Admin"
                                               asp-action="AddMeetingRoom">
                                            Toplantı Salonu Ekle
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        }

                    </ul>

                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <span class="nav-link text-info">
                                👤 @userName
                            </span>
                        </li>
                        <li class="nav-item">
                            <form asp-controller="Account" asp-action="Logout" method="post">
                                <button type="submit" class="btn btn-sm btn-danger ms-2">
                                    Çıkış
                                </button>
                            </form>
                        </li>
                    </ul>
                }

            </div>
        </div>
    </nav>

    <div class="container mt-4">
        @RenderBody()
    </div>

    <footer class="text-center mt-5 mb-3 text-muted">
        © @DateTime.Now.Year - MRP Yönetim Sistemi
    </footer>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0/dist/js/select2.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @await RenderSectionAsync("Scripts", required: false)


</body>
</html>